// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return desktop;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg4N1X6WNNmzzGO4HFkXKoGUFyiX-2eFM',
    appId: '1:168130109686:web:a05830370e0a0664da8cd7',
    messagingSenderId: '168130109686',
    projectId: 'learnify-931c8',
    authDomain: 'learnify-931c8.firebaseapp.com',
    storageBucket: 'learnify-931c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6zy0FxEIRhOeEnSFgowZyovFjEyNP8pY',
    appId: '1:168130109686:android:6a86939b72e7a770da8cd7',
    messagingSenderId: '168130109686',
    projectId: 'learnify-931c8',
    storageBucket: 'learnify-931c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI5Ah91PtXKua5qV1oFHTlrE3xZJMBVLA',
    appId: '1:168130109686:ios:52cd1300b5a6aa98da8cd7',
    messagingSenderId: '168130109686',
    projectId: 'learnify-931c8',
    storageBucket: 'learnify-931c8.appspot.com',
    iosClientId: '168130109686-9arbprhvgjuu7d5b9pohlk98kugmpbau.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnify',
  );

  static const FirebaseOptions desktop = FirebaseOptions(
    apiKey: 'AIzaSyCI5Ah91PtXKua5qV1oFHTlrE3xZJMBVLA',
    appId: '1:168130109686:ios:52cd1300b5a6aa98da8cd7',
    messagingSenderId: '168130109686',
    projectId: 'learnify-931c8',
    storageBucket: 'learnify-931c8.appspot.com',
    iosClientId: '168130109686-9arbprhvgjuu7d5b9pohlk98kugmpbau.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnify',
  );
}
