// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFvoWhQuIMQ6eo3qiIAFvbNHvkY268uzE',
    appId: '1:507422081167:web:13df4c42e037cbeaa430fa',
    messagingSenderId: '507422081167',
    projectId: 'learnify-66272',
    authDomain: 'learnify-66272.firebaseapp.com',
    storageBucket: 'learnify-66272.appspot.com',
    measurementId: 'G-QJY787PGDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdoALSThJxXR-c6VfhTdU8vEJZLU49xnw',
    appId: '1:507422081167:android:76ce2b65aa8eb0c8a430fa',
    messagingSenderId: '507422081167',
    projectId: 'learnify-66272',
    storageBucket: 'learnify-66272.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4xLu4SNjDd3G154ScP3RXukTaOq-5XVo',
    appId: '1:507422081167:ios:03d8779c4439fd8da430fa',
    messagingSenderId: '507422081167',
    projectId: 'learnify-66272',
    storageBucket: 'learnify-66272.appspot.com',
    iosClientId:
        '507422081167-diush7td5bdo379rnf04ig58rfldfe6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4xLu4SNjDd3G154ScP3RXukTaOq-5XVo',
    appId: '1:507422081167:ios:03d8779c4439fd8da430fa',
    messagingSenderId: '507422081167',
    projectId: 'learnify-66272',
    storageBucket: 'learnify-66272.appspot.com',
    iosClientId:
        '507422081167-diush7td5bdo379rnf04ig58rfldfe6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFvoWhQuIMQ6eo3qiIAFvbNHvkY268uzE',
    appId: '1:507422081167:web:554fcaa6c6658f18a430fa',
    messagingSenderId: '507422081167',
    projectId: 'learnify-66272',
    authDomain: 'learnify-66272.firebaseapp.com',
    storageBucket: 'learnify-66272.appspot.com',
    measurementId: 'G-81KXFQ7B8X',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAFvoWhQuIMQ6eo3qiIAFvbNHvkY268uzE',
    appId: '1:507422081167:web:6f324029be8bd224a430fa',
    messagingSenderId: '507422081167',
    projectId: 'learnify-66272',
    authDomain: 'learnify-66272.firebaseapp.com',
    storageBucket: 'learnify-66272.appspot.com',
    measurementId: 'G-2NJWVXDR0Z',
  );
}
